image:
- Visual Studio 2015  # for Python 2.7
- Ubuntu

build_script:
  - cmd: pip install .
  - sh: sudo pip install .

  # Then try install.py
  - python install.py -v ./install

test_script:
  - rez --version
  - rez env -- exit

  # Quickstart requires some setup
  - cmd: mkdir %USERPROFILE%\packages
  - sh: mkdir /home/appveyor/packages
  - rez bind --quickstart

  # Run selftest
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
  - cmd: rez selftest -s cmd
  - sh: rez selftest -s bash

build: Script
