---
trigger:
  branches:
    include: ["*"]
  paths:
    exclude:
      - .github/*
      - doc/*
      - wiki/*
      - .gitignore
      - LICENSE
      - README.md
      - CONTRIBUTING.md
      - CHANGELOG.md

jobs:
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python27:
          python.version: '2.7'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'

      - script: |
          sudo apt-get update
          sudo apt-get install -y tcsh csh cmake
        displayName: "Ubuntu Setup"

      - script: |
          pip install --upgrade pip
          pip install .
        displayName: 'pip install'

      - script: |
          rez selftest -vv
        displayName: 'selftest'

      # Finally, perform code coverage
      - script: |
          pip install coverage codecov
          coverage run -m rez selftest
          codecov
        displayName: 'CodeCov'
        condition: eq(variables['python.version'], '3.7')
        env:
            CODECOV_TOKEN: $(CODECOV_TOKEN)
