---
trigger:
  branches:
    include: ["*"]
  paths:
    exclude:
      - .github/*
      - doc/*
      - wiki/*
      - .gitignore
      - LICENSE
      - README.md
      - CONTRIBUTING.md
      - CHANGELOG.md

jobs:
  - job: Ubuntu
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      matrix:
        Python27:
          python.version: '2.7'
        Python35:
          python.version: '3.5'
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
        displayName: 'Use Python $(python.version)'

      - script: |
          apt-get update
          apt-get install -y software-properties-common
          add-apt-repository universe
          apt-get update
          apt-get install -y tcsh csh
        displayName: "Ubuntu Setup"

      - script: |
          python -m pip install --upgrade pip
          pip install .
        displayName: 'pip install'

      - script: |
          rez selftest -vv
        displayName: 'selftest'
